title: "Jasny Auth"
remote_theme: pmarsceill/just-the-docs
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Jasny Auth on GitHub":
    - "https://github.com/jasny/auth"
aux_links_new_tab: false

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/jasny/auth" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

